FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install wget -y
RUN apt install iputils-ping -y
RUN apt install lynx -y
RUN apt install mc -y
RUN apt install wireguard -y
RUN apt install systemctl -y
RUN apt install vi -y
RUN apt install nano -y

## Wireguard Confi noch kopieren...